### PR TITLE
Header and footer should not be visible on slide deck pages

### LINKED ISSUE #147: UX: header and footer should not be visible when on slide deck pages
The header and footer take up unnecessary screen space when looking at slides, so they should be hidden. However, the header should still be accessible in some form for navigation.

### PR DESCRIPTION
**Pull request by carpenterd777**
Fixes #147

Progress so far: Layout components are introduced for certain routes to use. If a route is indicated in the router as being a presentation, the header is hidden. The next step for the header is to have it slide out from the top of the page if the user hovers their mouse there for some time, so that the user can navigate away from the slides. Another potential solution is for a back arrow button to be placed to the left of the slides that takes the user back to the last route they visited on the site, or the home page if they had not yet navigated to any other page.

The footer is trickier to move. If its moved into the Layout components, then an old bug resurfaces where the footer is rendered before the rest of the page and the page is visibly messed up for a half second. But if the footer is left in `App`, then it becomes more difficult to control it showing up conditionally based on the current route and the `isPresentation`  indicator in the router. Any thoughts?

### CODE REVIEW

**Comment by dyc3** [comment]
I don't think this is a good approach. It would be easier to set global state to hide or show the header and footer.

**Comment by carpenterd777** [comment]
Would the global state be declared in `App.js`? How would you modify it?

**Comment by dyc3** [comment]
This appears to be what we're looking for: https://reactjs.org/docs/context.html

**Comment by dyc3** [comment]
I'm closing this because it's based off of a version of the site where we had the nested folders, and I really don't feel like wrestling with git right now

**Pull request closed without merging**
