### PR TITLE
New visual design

### LINKED ISSUE #49: Move design away from material

### PR DESCRIPTION
**Pull request by dyc3**
The new design focuses on using monospace fonts and thin, brightly colored lines.

Box shadows, text shadows, and blocks of solid bright colors are forbidden.

Closes #49

### CODE REVIEW

**Comment by carpenterd777** [comment]
If we do move forward with this design, it might be in line with the design to change the "SEC" in the logo on our website to just have thin red borders instead of being solid colored letters. I think it might look nice. Our logo in general doesn't need to change though.

**Comment by dyc3** [comment]
Agree with the logo part.

My thinking with the monospace fonts was to kinda give an IDE feel. Actual code blocks are still denoted by a darker background and syntax highlighting

**Comment by dyc3** [comment]
I restyled the logo to match design specs.

**Comment by dyc3** [comment]
I'd still call that a banner :P 

I feel like that would make the banner bleed visually into the hero image on the home page or whatever content is on the page. Notice in your screenshot how the top of the images make a very sharp separation between the header and the content below.

I do feel like there needs to be some changes in the header though, I'm not sure what it should look like.

How would your idea look on mobile @SWiessler ?

**Pull request merged**
