### PR TITLE
Hideable header and footer

### LINKED ISSUE #146: UX: Slide deck pages should not be scrollable
This will be easier to fix when #147 is done

### LINKED ISSUE #147: UX: header and footer should not be visible when on slide deck pages
The header and footer take up unnecessary screen space when looking at slides, so they should be hidden. However, the header should still be accessible in some form for navigation.

### PR DESCRIPTION
**Pull request by dyc3**
fixes #147, and accidentally fixes #146 too

### CODE REVIEW

**Comment by carpenterd777** [comment]
Running it on my machine, it seems like the contextType of the _view_ must be changed in order for the header and the footer to be hidden - it wasn't hidden without me making this change. However, doing causes the new contextType to stick around for each new view.

**Comment by dyc3** [comment]
Oh, it only hides if you do a reload on the slides page, not if you navigate to it from another page.

**Comment by carpenterd777** [comment]
Maybe there could be a `SlideUxContext` and a `DefaultUxContext` and each context could be used accordingly for each view? Just a thought

**Comment by dyc3** [comment]
I think we should just make it hide the header and footer based off of the URL. It'll be so much easier

**Review by carpenterd777 — CHANGES_REQUESTED** [review]
Alright, we can hide the footer and header based on the URL

**Review by carpenterd777 — APPROVED** [review]
This seems to work for now, but it does not fix #146 if there is enough content on the slide.

**Pull request merged**
