### PR TITLE
Remove annoying outlines on buttons

### PR DESCRIPTION
**Pull request by dyc3**

### CODE REVIEW

**Comment by carpenterd777** [comment]
What does removing the outlines change? I looked into the outline style and read that it was similar to the border style except it's outside of the element's dimensions, but I don't see the outlines on our buttons. When I inspected the buttons in the header, I couldn't find an outline style specified for them either

**Comment by dyc3** [comment]
This removes the outline that appears when you click on the buttons. In firefox, is an ugly dotted outline. In chrome, it's a blue outline.

**Comment by carpenterd777** [comment]
Instead of removing it outright, maybe we can change it to a prettier one? If people try navigating the site's buttons using the tab key its hard to know where you are without an outline.

**Comment by dyc3** [comment]
Ah, thats a good point.

**Comment by dyc3** [comment]
I'm having trouble reproducing this in chrome. It only appears in firefox, and only on buttons with `to` set.

**Comment by dyc3** [comment]
Closing this to make an actual issue

**Pull request closed without merging**
